---
- name: install hugo
  command: go get -v github.com/spf13/hugo
  environment:
    GOPATH: /home/axion/go
  args:
    creates: /home/axion/go
  become: false

- name: add hugo to ~/bin
  file:
    state: link
    src: /home/axion/go/bin/hugo
    dest: /home/axion/bin/hugo
    mode: 0755
    remote_src: true
  become: false

- name: open port 80
  firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled
