---
- name: install os pkgs
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - tmux
    - mercurial

- name: install url pkgs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - https://packages.chef.io/stable/el/7/chefdk-0.17.17-1.el7.x86_64.rpm

- name: install pip pkgs
  pip:
    name: "{{ item }}"
  with_items:
    - molecule
